-- ============================================================================
-- Smart Home / IoT Device Monitoring System
-- Database: Oracle Database 21c Express Edition (PDB: XEPDB1, Schema: SMART_HOME)
-- Script: exact_count_all_17.sql
-- Description: Verification script to output row counts for all 17 tables
--              and the total relational row count across the database schema.
-- ============================================================================

SET LINESIZE 200;
SET PAGESIZE 100;
SET FEEDBACK OFF;

SELECT 'ALERTS' AS table_name, COUNT(*) AS exact_count FROM ALERTS
UNION ALL
SELECT 'ALERT_CATEGORIES', COUNT(*) FROM ALERT_CATEGORIES
UNION ALL
SELECT 'AUTOMATION_RULES', COUNT(*) FROM AUTOMATION_RULES
UNION ALL
SELECT 'CAMERAS', COUNT(*) FROM CAMERAS
UNION ALL
SELECT 'DEVICES', COUNT(*) FROM DEVICES
UNION ALL
SELECT 'HOMES', COUNT(*) FROM HOMES
UNION ALL
SELECT 'HOME_ACCESS', COUNT(*) FROM HOME_ACCESS
UNION ALL
SELECT 'MOTION_SENSORS', COUNT(*) FROM MOTION_SENSORS
UNION ALL
SELECT 'NOTIFICATION_PREFERENCES', COUNT(*) FROM NOTIFICATION_PREFERENCES
UNION ALL
SELECT 'ROOMS', COUNT(*) FROM ROOMS
UNION ALL
SELECT 'RULE_ACTIONS', COUNT(*) FROM RULE_ACTIONS
UNION ALL
SELECT 'SENSOR_READINGS', COUNT(*) FROM SENSOR_READINGS
UNION ALL
SELECT 'SMART_LIGHTS', COUNT(*) FROM SMART_LIGHTS
UNION ALL
SELECT 'TEMPERATURE_SENSORS', COUNT(*) FROM TEMPERATURE_SENSORS
UNION ALL
SELECT 'THERMOSTATS', COUNT(*) FROM THERMOSTATS
UNION ALL
SELECT 'USERS', COUNT(*) FROM USERS
UNION ALL
SELECT 'USER_CONTACT_NUMBERS', COUNT(*) FROM USER_CONTACT_NUMBERS;

SELECT SUM(cnt) AS total_database_rows FROM (
    SELECT COUNT(*) AS cnt FROM ALERTS
    UNION ALL SELECT COUNT(*) FROM ALERT_CATEGORIES
    UNION ALL SELECT COUNT(*) FROM AUTOMATION_RULES
    UNION ALL SELECT COUNT(*) FROM CAMERAS
    UNION ALL SELECT COUNT(*) FROM DEVICES
    UNION ALL SELECT COUNT(*) FROM HOMES
    UNION ALL SELECT COUNT(*) FROM HOME_ACCESS
    UNION ALL SELECT COUNT(*) FROM MOTION_SENSORS
    UNION ALL SELECT COUNT(*) FROM NOTIFICATION_PREFERENCES
    UNION ALL SELECT COUNT(*) FROM ROOMS
    UNION ALL SELECT COUNT(*) FROM RULE_ACTIONS
    UNION ALL SELECT COUNT(*) FROM SENSOR_READINGS
    UNION ALL SELECT COUNT(*) FROM SMART_LIGHTS
    UNION ALL SELECT COUNT(*) FROM TEMPERATURE_SENSORS
    UNION ALL SELECT COUNT(*) FROM THERMOSTATS
    UNION ALL SELECT COUNT(*) FROM USERS
    UNION ALL SELECT COUNT(*) FROM USER_CONTACT_NUMBERS
);

EXIT;
